#
# Module manifest for module 'MicrosoftTeams'
#
# Generated by: Microsoft Corporation
#
# Updated on: 6/30/2020
#

@{
# Script module or binary module file associated with this manifest.
RootModule = './MicrosoftTeams.psm1'

# Version number of this module.
ModuleVersion = '7.7.0'

# Supported PSEditions
CompatiblePSEditions = 'Core', 'Desktop'

# ID used to uniquely identify this module
GUID = 'd910df43-3ca6-4c9c-a2e3-e9f45a8e2ad9'

# Author of this module
Author = 'Microsoft Corporation'

# Company or vendor of this module
CompanyName = 'Microsoft Corporation'

# Copyright statement for this module
Copyright = 'Microsoft Corporation. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Microsoft Teams cmdlets module for Windows PowerShell and PowerShell Core.

For more information, please visit the following: https://docs.microsoft.com/MicrosoftTeams/teams-powershell-overview'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
DotNetFrameworkVersion = '4.7.2'

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
CLRVersion = '4.0'

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = 'Amd64'

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# Removed this script from here because this module is used in SAW machines as well where Contraint Language Mode is on.
# Because of CLM constraint we were not able to import Teams module to SAW machines, that is why removing this script.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
#NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport =  @(
    'Clear-CsOnlineTelephoneNumberOrder'
	,'Complete-CsOnlineTelephoneNumberOrder'
	,'Disable-CsOnlineSipDomain'
#preview	,'Disable-CsTeamsShiftsConnectionErrorReport'
	,'Enable-CsOnlineSipDomain'
	,'Export-CsAcquiredPhoneNumber'
	,'Export-CsAutoAttendantHolidays'
	,'Export-CsOnlineAudioFile'
	,'Find-CsGroup'
	,'Find-CsOnlineApplicationInstance'
	,'Get-CsApplicationAccessPolicy'
	,'Get-CsApplicationMeetingConfiguration'
	,'Get-CsAutoAttendant'
	,'Get-CsAutoAttendantHolidays'
	,'Get-CsAutoAttendantStatus'
	,'Get-CsAutoAttendantSupportedLanguage'
	,'Get-CsAutoAttendantSupportedTimeZone'
	,'Get-CsAutoAttendantTenantInformation'
	,'Get-CsAutoRecordingTemplate'
	,'Get-CsBatchPolicyAssignmentOperation'
	,'Get-CsCallingLineIdentity'
	,'Get-CsCallQueue'
	,'Get-CsCloudCallDataConnection'
	,'Get-CsEffectiveTenantDialPlan'
	,'Get-CsExportAcquiredPhoneNumberStatus'
	,'Get-CsGroupPolicyAssignment'
	,'Get-CsHybridTelephoneNumber'
	,'Get-CsInboundBlockedNumberPattern'
	,'Get-CsInboundExemptNumberPattern'
	,'Get-CsMainlineAttendantAppointmentBookingFlow'
	,'Get-CsMainlineAttendantFlow'
	,'Get-CsMainlineAttendantSupportedLanguages'
	,'Get-CsMainlineAttendantSupportedVoices'
	,'Get-CsMainlineAttendantTenantInformation'
	,'Get-CsMainlineAttendantQuestionAnswerFlow'
	,'Get-CsMeetingMigrationStatus'
	,'Get-CsOnlineApplicationInstance'
	,'Get-CsOnlineApplicationInstanceAssociation'
	,'Get-CsOnlineApplicationInstanceAssociationStatus'
	,'Get-CsOnlineAudioConferencingRoutingPolicy'
	,'Get-CsOnlineAudioFile'
	,'Get-CsOnlineDialInConferencingBridge'
	,'Get-CsOnlineDialInConferencingLanguagesSupported'
	,'Get-CsOnlineDialinConferencingPolicy'
	,'Get-CsOnlineDialInConferencingServiceNumber'
	,'Get-CsOnlineDialinConferencingTenantConfiguration'
	,'Get-CsOnlineDialInConferencingTenantSettings'
	,'Get-CsOnlineDialInConferencingUser'
	,'Get-CsOnlineDialOutPolicy'
	,'Get-CsOnlineDirectoryTenant'
	,'Get-CsOnlineEnhancedEmergencyServiceDisclaimer'
	,'Get-CsOnlineLisCivicAddress'
	,'Get-CsOnlineLisLocation'
	,'Get-CsOnlineLisPort'
	,'Get-CsOnlineLisSubnet'
	,'Get-CsOnlineLisSwitch'
	,'Get-CsOnlineLisWirelessAccessPoint'
	,'Get-CsOnlinePSTNGateway'
	,'Get-CsOnlinePstnUsage'
	,'Get-CsOnlineSchedule'
	,'Get-CsOnlineSipDomain'
	,'Get-CsOnlineTelephoneNumber'
	,'Get-CsOnlineTelephoneNumberCountry'
	,'Get-CsOnlineTelephoneNumberOrder'
	,'Get-CsOnlineTelephoneNumberType'
	,'Get-CsOnlineUser'
	,'Get-CsOnlineVoicemailUserSettings'
	,'Get-CsOnlineVoiceRoute'
	,'Get-CsOnlineVoiceRoutingPolicy'
	,'Get-CsOnlineVoiceUser'
	,'Get-CsPhoneNumberAssignment'
	,'Get-CsPhoneNumberPolicyAssignment'
	,'Get-CsPhoneNumberTag'
	,'Get-CsPhoneNumberTenantConfiguration'
	,'Get-CsPolicyPackage'
	,'Get-CsSdgBulkSignInRequestStatus'
	,'Get-CsSDGBulkSignInRequestsSummary'
	,'Get-CsTeamsAudioConferencingPolicy'
	,'Get-CsTeamsCallParkPolicy'
	,'Get-CsTeamsCortanaPolicy'	
	,'Get-CsTeamsEmergencyCallRoutingPolicy'
	,'Get-CsTeamsEnhancedEncryptionPolicy'
	,'Get-CsTeamsGuestCallingConfiguration'
	,'Get-CsTeamsGuestMessagingConfiguration'
	,'Get-CsTeamsIPPhonePolicy'
	,'Get-CsTeamsMediaLoggingPolicy'
	,'Get-CsTeamsMeetingBroadcastConfiguration'
	,'Get-CsTeamsMeetingBroadcastPolicy'
	,'Get-CsTeamsMigrationConfiguration'
	,'Get-CsTeamsNetworkRoamingPolicy'
	,'Get-CsTeamsRoomVideoTeleConferencingPolicy'
	,'Get-CsTeamsSettingsCustomApp'
	,'Get-CsTeamsShiftsAppPolicy'
	,'Get-CsTeamsShiftsConnectionConnector'
	,'Get-CsTeamsShiftsConnectionErrorReport'
	,'Get-CsTeamsShiftsConnection'
	,'Get-CsTeamsShiftsConnectionInstance'
	,'Get-CsTeamsShiftsConnectionOperation'
	,'Get-CsTeamsShiftsConnectionSyncResult'
	,'Get-CsTeamsShiftsConnectionTeamMap'
	,'Get-CsTeamsShiftsConnectionWfmTeam'
	,'Get-CsTeamsShiftsConnectionWfmUser'
	,'Get-CsTeamsSurvivableBranchAppliance'
	,'Get-CsTeamsSurvivableBranchAppliancePolicy'
	,'Get-CsTeamsTargetingPolicy'
	,'Get-CsTeamsTranslationRule'
	,'Get-CsTeamsUnassignedNumberTreatment'
	,'Get-CsTeamsUpgradePolicy'
	,'Get-CsTeamsVdiPolicy'
	,'Get-CsTeamsVideoInteropServicePolicy'
	,'Get-CsTeamsWorkLoadPolicy'
	,'Get-CsTeamTemplate'
	,'Get-CsTeamTemplateList'
	,'Get-CsTenant'
	,'Get-CsTenantBlockedCallingNumbers'
	,'Get-CsTenantDialPlan'
	,'Get-CsTenantFederationConfiguration'
	,'Get-CsTenantLicensingConfiguration'
	,'Get-CsTenantMigrationConfiguration'
	,'Get-CsTenantNetworkConfiguration'
	,'Get-CsTenantNetworkRegion'
	,'Get-CsTenantNetworkSubnet'
	,'Get-CsTenantTrustedIPAddress'
	,'Get-CsUserCallingSettings'
	,'Get-CsUserPolicyAssignment'
	,'Get-CsUserPolicyPackage'
	,'Get-CsUserPolicyPackageRecommendation'
	,'Get-CsVideoInteropServiceProvider'
	,'Get-CsAgent'
	,'Get-CsAiAgents'
	,'Grant-CsApplicationAccessPolicy'
	,'Get-CsComplianceRecordingForCallQueueTemplate'
	,'Get-CsSharedCallQueueHistoryTemplate'
	,'Get-CsTagsTemplate'
	,'Get-CsSharedCallHistoryTemplate'
	,'Grant-CsCallingLineIdentity'
	,'Grant-CsDialoutPolicy'
	,'Grant-CsGroupPolicyPackageAssignment'
	,'Grant-CsOnlineAudioConferencingRoutingPolicy'
	,'Grant-CsOnlineVoicemailPolicy'
	,'Grant-CsOnlineVoiceRoutingPolicy'
	,'Grant-CsTeamsAudioConferencingPolicy'
	,'Grant-CsTeamsCallHoldPolicy'
	,'Grant-CsTeamsCallParkPolicy'
	,'Grant-CsTeamsChannelsPolicy'
	,'Grant-CsTeamsCortanaPolicy'
	,'Grant-CsTeamsEmergencyCallingPolicy'
	,'Grant-CsTeamsEmergencyCallRoutingPolicy'
	,'Grant-CsTeamsEnhancedEncryptionPolicy'
	,'Grant-CsTeamsFeedbackPolicy'
	,'Grant-CsTeamsIPPhonePolicy'
	,'Grant-CsTeamsMediaLoggingPolicy'
	,'Grant-CsTeamsMeetingBroadcastPolicy'
	,'Grant-CsTeamsMeetingPolicy'
	,'Grant-CsTeamsMessagingPolicy'
	,'Grant-CsTeamsRoomVideoTeleConferencingPolicy'
	,'Grant-CsTeamsSurvivableBranchAppliancePolicy'
	,'Grant-CsTeamsUpdateManagementPolicy'
	,'Grant-CsTeamsUpgradePolicy'
	,'Grant-CsTeamsVideoInteropServicePolicy'
	,'Grant-CsTeamsVoiceApplicationsPolicy'
	,'Grant-CsTeamsWorkLoadPolicy'
	,'Grant-CsTenantDialPlan'
	,'Grant-CsUserPolicyPackage'
    ,'Grant-CsTeamsComplianceRecordingPolicy'
	,'Import-CsAutoAttendantHolidays'
	,'Import-CsOnlineAudioFile'
	,'Invoke-CsInternalPSTelemetry'
	,'Move-CsInternalHelper'
	,'New-CsAgent'
	,'New-CsApplicationAccessPolicy'
	,'New-CsAutoAttendant'
	,'New-CsAutoAttendantCallableEntity'
	,'New-CsAutoAttendantCallFlow'
	,'New-CsAutoAttendantCallHandlingAssociation'
	,'New-CsAutoAttendantDialScope'
	,'New-CsAutoAttendantMenu'
	,'New-CsAutoAttendantMenuOption'
	,'New-CsAutoAttendantPrompt'
	,'New-CsAutoRecordingTemplate'
	,'New-CsBatchPolicyAssignmentOperation'
	,'New-CsBatchPolicyPackageAssignmentOperation'
	,'New-CsCallingLineIdentity'
	,'New-CsCallQueue'
	,'New-CsCloudCallDataConnection'
	,'New-CsCustomPolicyPackage'
	,'New-CsEdgeAllowAllKnownDomains'
	,'New-CsEdgeAllowList'
	,'New-CsEdgeDomainPattern'
	,'New-CsGroupPolicyAssignment'
	,'New-CsHybridTelephoneNumber'
	,'New-CsInboundBlockedNumberPattern'
	,'New-CsInboundExemptNumberPattern'
	,'New-CsMainlineAttendantAppointmentBookingFlow'
	,'New-CsMainlineAttendantQuestionAnswerFlow'
	,'New-CsOnlineApplicationInstance'
	,'New-CsOnlineApplicationInstanceAssociation'
	,'New-CsOnlineAudioConferencingRoutingPolicy'
	,'New-CsOnlineDateTimeRange'
	,'New-CsOnlineLisCivicAddress'
	,'New-CsOnlineLisLocation'
	,'New-CsOnlinePSTNGateway'
	,'New-CsOnlineSchedule'
	,'New-CsOnlineTelephoneNumberOrder'
	,'New-CsOnlineTimeRange'
	,'New-CsOnlineVoiceRoute'
	,'New-CsOnlineVoiceRoutingPolicy'
	,'New-CsSdgBulkSignInRequest'
	,'New-CsTeamsAudioConferencingPolicy'
	,'New-CsTeamsCallParkPolicy'
	,'New-CsTeamsCortanaPolicy'
	,'New-CsTeamsEmergencyCallRoutingPolicy'
	,'New-CsTeamsEmergencyNumber'
	,'New-CsTeamsEnhancedEncryptionPolicy'
	,'New-CsTeamsIPPhonePolicy'
	,'New-CsTeamsMeetingBroadcastPolicy'
	,'New-CsTeamsNetworkRoamingPolicy'
	,'New-CsTeamsRoomVideoTeleConferencingPolicy'
	,'New-CsTeamsShiftsConnectionBatchTeamMap'
	,'New-CsTeamsShiftsConnection'
	,'New-CsTeamsShiftsConnectionInstance'
	,'New-CsTeamsSurvivableBranchAppliance'
	,'New-CsTeamsSurvivableBranchAppliancePolicy'
	,'New-CsTeamsTranslationRule'
	,'New-CsTeamsUnassignedNumberTreatment'
	,'New-CsTeamsVdiPolicy'
	,'New-CsTeamsWorkLoadPolicy'
	,'New-CsTeamTemplate'
	,'New-CsTenantDialPlan'
	,'New-CsTenantNetworkRegion'
	,'New-CsTenantNetworkSite'
	,'New-CsTenantNetworkSubnet'
	,'New-CsTenantTrustedIPAddress'
	,'New-CsUserCallingDelegate'
	,'New-CsVideoInteropServiceProvider'
	,'New-CsVoiceNormalizationRule'
	,'New-CsOnlineDirectRoutingTelephoneNumberUploadOrder'
	,'New-CsOnlineTelephoneNumberReleaseOrder'
	,'New-CsComplianceRecordingForCallQueueTemplate'
	,'New-CsTagsTemplate'
	,'New-CsTag'
	,'New-CsSharedCallQueueHistoryTemplate'
	,'New-CsSharedCallHistoryTemplate'
	,'Register-CsOnlineDialInConferencingServiceNumber'
	,'Remove-CsAgent'
	,'Remove-CsApplicationAccessPolicy'
	,'Remove-CsAutoAttendant'
	,'Remove-CsAutoRecordingTemplate'
	,'Remove-CsCallingLineIdentity'
	,'Remove-CsCallQueue'
	,'Remove-CsCustomPolicyPackage'
	,'Remove-CsGroupPolicyAssignment'
	,'Remove-CsHybridTelephoneNumber'
	,'Remove-CsInboundBlockedNumberPattern'
	,'Remove-CsInboundExemptNumberPattern'
	,'Remove-CsMainlineAttendantAppointmentBookingFlow'
	,'Remove-CsMainlineAttendantQuestionAnswerFlow'
	,'Remove-CsOnlineApplicationInstanceAssociation'
	,'Remove-CsOnlineAudioConferencingRoutingPolicy'
	,'Remove-CsOnlineAudioFile'
	,'Remove-CsOnlineDialInConferencingTenantSettings'
	,'Remove-CsOnlineLisCivicAddress'
	,'Remove-CsOnlineLisLocation'
	,'Remove-CsOnlineLisPort'
	,'Remove-CsOnlineLisSubnet'
	,'Remove-CsOnlineLisSwitch'
	,'Remove-CsOnlineLisWirelessAccessPoint'
	,'Remove-CsOnlinePSTNGateway'
	,'Remove-CsOnlineSchedule'
	,'Remove-CsOnlineTelephoneNumber'
	,'Remove-CsOnlineVoiceRoute'
	,'Remove-CsOnlineVoiceRoutingPolicy'
	,'Remove-CsPhoneNumberAssignment'
	,'Remove-CsPhoneNumberAssignmentBlock'
	,'Remove-CsPhoneNumberSmsActivation'
	,'Remove-CsPhoneNumberTag'
	,'Remove-CsPhoneNumberTenantConfiguration'
	,'Remove-CsTeamsAudioConferencingPolicy'
	,'Remove-CsTeamsCallParkPolicy'
	,'Remove-CsTeamsCortanaPolicy'
	,'Remove-CsTeamsEmergencyCallRoutingPolicy'
	,'Remove-CsTeamsEnhancedEncryptionPolicy'
	,'Remove-CsTeamsIPPhonePolicy'
	,'Remove-CsTeamsMeetingBroadcastPolicy'
	,'Remove-CsTeamsNetworkRoamingPolicy'
	,'Remove-CsTeamsRoomVideoTeleConferencingPolicy'
	,'Remove-CsTeamsShiftsConnection'
    ,'Remove-CsTeamsShiftsConnectionInstance'
    ,'Remove-CsTeamsShiftsConnectionTeamMap'
	,'Remove-CsTeamsShiftsScheduleRecord'
	,'Remove-CsTeamsSurvivableBranchAppliance'
	,'Remove-CsTeamsSurvivableBranchAppliancePolicy'
	,'Remove-CsTeamsTargetingPolicy'
	,'Remove-CsTeamsTranslationRule'
	,'Remove-CsTeamsUnassignedNumberTreatment'
	,'Remove-CsTeamsVdiPolicy'
	,'Remove-CsTeamsWorkLoadPolicy'
	,'Remove-CsTeamTemplate'
	,'Remove-CsTenantDialPlan'
	,'Remove-CsTenantNetworkRegion'
	,'Remove-CsTenantNetworkSite'
	,'Remove-CsTenantNetworkSubnet'
	,'Remove-CsTenantTrustedIPAddress'
	,'Remove-CsUserCallingDelegate'
	,'Remove-CsUserLicenseGracePeriod'
	,'Remove-CsVideoInteropServiceProvider'
	,'Remove-CsComplianceRecordingForCallQueueTemplate'
	,'Remove-CsTagsTemplate'
	,'Remove-CsSharedCallQueueHistoryTemplate'
	,'Remove-CsSharedCallHistoryTemplate'
	,'Set-CsAgent'
	,'Set-CsApplicationAccessPolicy'
	,'Set-CsApplicationMeetingConfiguration'
	,'Set-CsAutoAttendant'
	,'Set-CsAutoRecordingTemplate'
	,'Set-CsCallingLineIdentity'
	,'Set-CsCallQueue'
	,'Set-CsInboundBlockedNumberPattern'
	,'Set-CsInboundExemptNumberPattern'
	,'Set-CsMainlineAttendantAppointmentBookingFlow'
	,'Set-CsMainlineAttendantQuestionAnswerFlow'
	,'Set-CsOnlineApplicationInstance'
	,'Set-CsOnlineAudioConferencingRoutingPolicy'
	,'Set-CsOnlineDialInConferencingBridge'
	,'Set-CsOnlineDialInConferencingServiceNumber'
	,'Set-CsOnlineDialInConferencingTenantSettings'
	,'Set-CsOnlineDialInConferencingUser'
	,'Set-CsOnlineDialInConferencingUserDefaultNumber'
	,'Set-CsOnlineEnhancedEmergencyServiceDisclaimer'
	,'Set-CsOnlineLisCivicAddress'
	,'Set-CsOnlineLisLocation'
	,'Set-CsOnlineLisPort'
	,'Set-CsOnlineLisSubnet'
	,'Set-CsOnlineLisSwitch'
	,'Set-CsOnlineLisWirelessAccessPoint'
	,'Set-CsOnlinePSTNGateway'
	,'Set-CsOnlinePstnUsage'
	,'Set-CsOnlineSchedule'
	,'Set-CsOnlineVoiceApplicationInstance'
	,'Set-CsOnlineVoicemailUserSettings'
	,'Set-CsOnlineVoiceRoute'
	,'Set-CsOnlineVoiceRoutingPolicy'
	,'Set-CsOnlineVoiceUser'
	,'Set-CsPhoneNumberAssignment'
	,'Set-CsPhoneNumberAssignmentBlock'
	,'Set-CsPhoneNumberPolicyAssignment'
	,'Set-CsPhoneNumberSmsActivation'
	,'Set-CsPhoneNumberTag'
	,'Set-CsPhoneNumberTenantConfiguration'
	,'Set-CsTeamsAudioConferencingPolicy'
	,'Set-CsTeamsCallParkPolicy'
	,'Set-CsTeamsCortanaPolicy'	
	,'Set-CsTeamsEmergencyCallRoutingPolicy'
	,'Set-CsTeamsEnhancedEncryptionPolicy'
	,'Set-CsTeamsGuestCallingConfiguration'
	,'Set-CsTeamsGuestMessagingConfiguration'
	,'Set-CsTeamsIPPhonePolicy'
	,'Set-CsTeamsMeetingBroadcastConfiguration'
	,'Set-CsTeamsMeetingBroadcastPolicy'
	,'Set-CsTeamsMigrationConfiguration'
	,'Set-CsTeamsNetworkRoamingPolicy'
	,'Set-CsTeamsRoomVideoTeleConferencingPolicy'
	,'Set-CsTeamsSettingsCustomApp'
	,'Set-CsTeamsShiftsAppPolicy'
 	,'Set-CsTeamsShiftsConnection'
	,'Set-CsTeamsShiftsConnectionInstance'
	,'Set-CsTeamsSurvivableBranchAppliance'
	,'Set-CsTeamsSurvivableBranchAppliancePolicy'
	,'Set-CsTeamsTargetingPolicy'
	,'Set-CsTeamsTranslationRule'
	,'Set-CsTeamsUnassignedNumberTreatment'
	,'Set-CsTeamsVdiPolicy'
	,'Set-CsTeamsWorkLoadPolicy'
	,'Set-CsTenantBlockedCallingNumbers'
	,'Set-CsTenantDialPlan'
	,'Set-CsTenantFederationConfiguration'
	,'Set-CsTenantMigrationConfiguration'
	,'Set-CsTenantNetworkRegion'
	,'Set-CsTenantNetworkSite'
	,'Set-CsTenantNetworkSubnet'
	,'Set-CsTenantTrustedIPAddress'
	,'Set-CsUser'
	,'Set-CsUserCallingDelegate'
	,'Set-CsUserCallingSettings'
	,'Set-CsVideoInteropServiceProvider'
	,'Set-CsComplianceRecordingForCallQueueTemplate'
	,'Set-CsTagsTemplate'
	,'Set-CsSharedCallQueueHistoryTemplate'
	,'Set-CsSharedCallHistoryTemplate'
	,'Start-CsExMeetingMigration'
	,'Sync-CsOnlineApplicationInstance'
	,'Test-CsEffectiveTenantDialPlan'
	,'Test-CsInboundBlockedNumberPattern'
    ,'Test-CsTeamsShiftsConnectionValidate'
	,'Test-CsTeamsTranslationRule'
	,'Test-CsTeamsUnassignedNumberTreatment'
	,'Test-CsVoiceNormalizationRule'
	,'Unregister-CsOnlineDialInConferencingServiceNumber'
	,'Update-CsAutoAttendant'
	,'Update-CsCustomPolicyPackage'
	,'Update-CsPhoneNumberTag'
	,'Update-CsTeamsShiftsConnection'
	,'Update-CsTeamsShiftsConnectionInstance'
	,'Update-CsTeamTemplate'
	,'New-CsBatchTeamsDeployment'
	,'Get-CsBatchTeamsDeploymentStatus'
	,'Get-CsPersonalAttendantSettings'
	,'Set-CsPersonalAttendantSettings'
#OCE related functions exports start here. DO NOT MODIFY!
    ,'Set-CsOCEContext'
    ,'Clear-CsOCEContext'
	,'Get-CsRegionContext'
	,'Set-CsRegionContext'
	,'Clear-CsRegionContext'
    ,'Get-CsMeetingMigrationTransactionHistory'
	,'Get-CsMasVersionedSchemaData'
	,'Get-CsMasObjectChangelog'
	,'Get-CsBusinessVoiceDirectoryDiagnosticData'
	,'Get-CsCloudTenant'
	,'Get-CsCloudUser'
	,'Get-CsHostingProvider'
    ,'Set-CsTenantUserBackfill'
	,'Invoke-CsCustomHandlerNgtprov'
	,'Invoke-CsCustomHandlerCallBackNgtprov'
	,'New-CsSdgDeviceTaggingRequest'
    ,'Get-CsMoveTenantServiceInstanceTaskStatus'
	,'Move-CsTenantServiceInstance'
	,'Move-CsTenantCrossRegion'
	,'Invoke-CsDirectObjectSync'
	,'New-CsSDGDeviceTransferRequest'
	,'Get-CsAadTenant'
	,'Get-CsAadUser'
	,'Clear-CsCacheOperation'
	,'Move-CsAvsTenantPartition'
	,'Invoke-CsMsodsSync'
	,'Get-CsUssUserSettings'
	,'Set-CsUssUserSettings'
	,'Invoke-CsRehomeuser'
	,'Set-CsNotifyCache'
#OCE exports end
)
# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @(
    'Add-TeamChannelUser'
    ,'Add-TeamUser'
    ,'Connect-MicrosoftTeams'
    ,'Disconnect-MicrosoftTeams'
    ,'Set-TeamsEnvironmentConfig'
    ,'Clear-TeamsEnvironmentConfig'
    ,'Get-AssociatedTeam'
    ,'Get-MultiGeoRegion'
    ,'Get-Operation'
    ,'Get-SharedWithTeam'
    ,'Get-SharedWithTeamUser'
    ,'Get-Team'
    ,'Get-TeamAllChannel'
    ,'Get-TeamChannel'
    ,'Get-TeamChannelUser'
    ,'Get-TeamIncomingChannel'
    ,'Get-TeamsApp'
	,'Get-TeamsArtifacts'
    ,'Get-TeamUser'
	,'Get-M365TeamsApp'
	,'Get-AllM365TeamsApps'
	,'Get-M365UnifiedTenantSettings'
	,'Get-M365UnifiedCustomPendingApps'
    ,'Get-CsTeamsAcsFederationConfiguration'
    ,'Get-CsTeamsMessagingPolicy'
    ,'Get-CsTeamsMeetingPolicy'
    ,'Get-CsOnlineVoicemailPolicy'
    ,'Get-CsOnlineVoicemailValidationConfiguration'
	,'Get-CsTeamsAIPolicy'
    ,'Get-CsTeamsFeedbackPolicy'
    ,'Get-CsTeamsUpdateManagementPolicy'
    ,'Get-CsTeamsChannelsPolicy'
    ,'Get-CsTeamsMeetingBrandingPolicy'
    ,'Get-CsTeamsEmergencyCallingPolicy'
    ,'Get-CsTeamsCallHoldPolicy'
    ,'Get-CsTeamsMessagingConfiguration'
	,'Get-CsTeamsVoiceApplicationsPolicy'
    ,'Get-CsTeamsEventsPolicy'
	,'Get-CsTeamsExternalAccessConfiguration'
	,'Get-CsTeamsFilesPolicy'
    ,'Get-CsTeamsCallingPolicy'
	,'Get-CsTeamsClientConfiguration'
    ,'Get-CsExternalAccessPolicy'
    ,'Get-CsTeamsAppPermissionPolicy'
    ,'Get-CsTeamsAppSetupPolicy'
    ,'Get-CsTeamsFirstPartyMeetingTemplateConfiguration'
    ,'Get-CsTeamsMeetingTemplatePermissionPolicy'
    ,'Get-CsLocationPolicy'
    ,'Get-CsTeamsShiftsPolicy'
    ,'Get-CsTenantNetworkSite'
    ,'Get-CsTeamsCarrierEmergencyCallRoutingPolicy'
    ,'Get-CsTeamsMeetingTemplateConfiguration'
    ,'Get-CsTeamsFirstPartyMeetingTemplateConfiguration'
    ,'Get-CsTeamsVirtualAppointmentsPolicy'
    ,'Get-CsTeamsSharedCallingRoutingPolicy'
    ,'Get-CsTeamsTemplatePermissionPolicy'
	,'Get-CsTeamsComplianceRecordingPolicy'
	,'Get-CsTeamsComplianceRecordingApplication'
	,'Get-CsTeamsEducationAssignmentsAppPolicy'
	,'Get-CsTeamsUpgradeConfiguration'
	,'Get-CsTeamsAudioConferencingCustomPromptsConfiguration'
	,'Get-CsTeamsSipDevicesConfiguration'
	,'Get-CsTeamsCustomBannerText'
    ,'Get-CsTeamsGuestMeetingConfiguration'
    ,'Get-CsTeamsVdiPolicy'
	,'Get-CsTeamsMediaConnectivityPolicy'
    ,'Get-CsTeamsMeetingConfiguration'
	,'Get-CsTeamsMobilityPolicy'
	,'Get-CsTeamsWorkLocationDetectionPolicy'
    ,'Get-CsTeamsRecordingRollOutPolicy'
	,'Get-CsTeamsRemoteLogCollectionConfiguration'
	,'Get-CsTeamsRemoteLogCollectionDevice'
	,'Get-CsTeamsRecordingAndTranscriptionCustomMessage'
    ,'Get-CsTeamsEducationConfiguration'
    ,'Get-CsTeamsBYODAndDesksPolicy'
    ,'Get-CsTeamsNotificationAndFeedsPolicy'
	,'Get-CsTeamsMultiTenantOrganizationConfiguration'
	,'Get-CsTeamsPersonalAttendantPolicy'
    ,'Get-CsPrivacyConfiguration'
	,'Get-DirectToGroupAssignmentsMigrationStatus'
    ,'Get-GroupAssignmentRecommendationsPerPolicyName'
    ,'Get-GroupAssignmentRecommendationsPerPolicyType'
    ,'Get-GroupPolicyAssignmentConflict'
	,'Grant-CsTeamsAIPolicy'
    ,'Grant-CsTeamsMeetingBrandingPolicy'
    ,'Grant-CsExternalAccessPolicy'
    ,'Grant-CsTeamsCallingPolicy'
	,'Grant-CsTeamsAppPermissionPolicy'
	,'Grant-CsTeamsAppSetupPolicy'
    ,'Grant-CsTeamsEventsPolicy'
	,'Grant-CsTeamsFilesPolicy'
	,'Grant-CsTeamsMediaConnectivityPolicy'
    ,'Grant-CsTeamsMeetingTemplatePermissionPolicy'
    ,'Grant-CsTeamsCarrierEmergencyCallRoutingPolicy'
    ,'Grant-CsTeamsVirtualAppointmentsPolicy'
    ,'Grant-CsTeamsSharedCallingRoutingPolicy'
    ,'Grant-CsTeamsShiftsPolicy'
    ,'Grant-CsTeamsRecordingRollOutPolicy'
	,'Grant-CsTeamsVdiPolicy'
	,'Grant-CsTeamsWorkLocationDetectionPolicy'
    ,'Grant-CsTeamsBYODAndDesksPolicy'
	,'Grant-CsTeamsPersonalAttendantPolicy'
    ,'Grant-CsTeamsMobilityPolicy'
	,'Invoke-ClearDirectToGroupAssignmentMigration'
	,'Invoke-StartDirectToGroupAssignmentMigration'
    ,'New-Team'
    ,'New-TeamChannel'
    ,'New-TeamsApp'
	,'New-CsPhoneNumberBulkUpdateTagsOrder'
	,'New-CsTeamsAIPolicy'
    ,'New-CsTeamsMessagingPolicy'
    ,'New-CsTeamsMeetingPolicy'
    ,'New-CsOnlineVoicemailPolicy'
    ,'New-CsTeamsFeedbackPolicy'
    ,'New-CsTeamsUpdateManagementPolicy'
    ,'New-CsTeamsChannelsPolicy'
	,'New-CsTeamsFilesPolicy'
	,'New-CsTeamsMediaConnectivityPolicy'
    ,'New-CsTeamsMeetingBrandingTheme'
    ,'New-CsTeamsMeetingBackgroundImage'
	,'New-CsTeamsMobilityPolicy'
    ,'New-CsTeamsNdiAssuranceSlate'
    ,'New-CsTeamsMeetingBrandingPolicy'
    ,'New-CsTeamsEmergencyCallingPolicy'
    ,'New-CsTeamsEmergencyCallingExtendedNotification'
    ,'New-CsTeamsCallHoldPolicy'
    ,'New-CsTeamsVoiceApplicationsPolicy'
    ,'New-CsTeamsEventsPolicy'
    ,'New-CsTeamsCallingPolicy'
    ,'New-CsExternalAccessPolicy'
    ,'New-CsTeamsAppPermissionPolicy'
    ,'New-CsTeamsAppSetupPolicy'
    ,'New-CsTeamsMeetingTemplatePermissionPolicy'
    ,'New-CsLocationPolicy'
    ,'New-CsTeamsCarrierEmergencyCallRoutingPolicy'
    ,'New-CsTeamsHiddenMeetingTemplate'
    ,'New-CsTeamsVirtualAppointmentsPolicy'
    ,'New-CsTeamsSharedCallingRoutingPolicy'
    ,'New-CsTeamsHiddenTemplate'
    ,'New-CsTeamsTemplatePermissionPolicy'
	,'New-CsTeamsComplianceRecordingPolicy'
	,'New-CsTeamsComplianceRecordingApplication'
	,'New-CsTeamsComplianceRecordingPairedApplication'
	,'New-CsTeamsWorkLocationDetectionPolicy'
    ,'New-CsTeamsRecordingRollOutPolicy'
	,'New-CsTeamsRemoteLogCollectionDevice'
	,'New-CsTeamsRecordingAndTranscriptionCustomMessage'
	,'New-CsTeamsRecordingAndTranscriptionLocalizationCustomMessage'
	,"New-CsCustomPrompt"
    ,"New-CsCustomPromptPackage"
	,'New-CsTeamsShiftsPolicy'
	,'New-CsTeamsCustomBannerText'
	,'New-CsTeamsVdiPolicy'
    ,'New-CsTeamsBYODAndDesksPolicy'
	,'New-CsTeamsPersonalAttendantPolicy'
    ,'Remove-SharedWithTeam'
    ,'Remove-Team'
    ,'Remove-TeamChannel'
    ,'Remove-TeamChannelUser'
    ,'Remove-TeamsApp'
    ,'Remove-TeamUser'
	,'Remove-CsTeamsAIPolicy'
    ,'Remove-CsTeamsMessagingPolicy'
    ,'Remove-CsTeamsMeetingPolicy'
    ,'Remove-CsOnlineVoicemailPolicy'
    ,'Remove-CsTeamsFeedbackPolicy'
	,'Remove-CsTeamsFilesPolicy'
    ,'Remove-CsTeamsUpdateManagementPolicy'
    ,'Remove-CsTeamsChannelsPolicy'
	,'Remove-CsTeamsMediaConnectivityPolicy'
    ,'Remove-CsTeamsMeetingBrandingPolicy'
    ,'Remove-CsTeamsEmergencyCallingPolicy'
    ,'Remove-CsTeamsCallHoldPolicy'
    ,'Remove-CsTeamsVoiceApplicationsPolicy'
    ,'Remove-CsTeamsEventsPolicy'
    ,'Remove-CsTeamsCallingPolicy'
    ,'Remove-CsExternalAccessPolicy'
    ,'Remove-CsTeamsAppPermissionPolicy'
    ,'Remove-CsTeamsAppSetupPolicy'
    ,'Remove-CsTeamsMeetingTemplatePermissionPolicy'
	,'Remove-CsTeamsMobilityPolicy'
    ,'Remove-CsLocationPolicy'
    ,'Remove-CsTeamsCarrierEmergencyCallRoutingPolicy'
    ,'Remove-CsTeamsVirtualAppointmentsPolicy'
    ,'Remove-CsTeamsSharedCallingRoutingPolicy'
    ,'Remove-CsTeamsTemplatePermissionPolicy'
	,'Remove-CsTeamsComplianceRecordingPolicy'
	,'Remove-CsTeamsComplianceRecordingApplication'
	,'Remove-CsTeamsShiftsPolicy'
	,'Remove-CsTeamsCustomBannerText'
    ,'Remove-CsTeamsVdiPolicy'
	,'Remove-CsTeamsWorkLocationDetectionPolicy'
    ,'Remove-CsTeamsRecordingRollOutPolicy'
	,'Remove-CsTeamsRemoteLogCollectionDevice'
	,'Remove-CsTeamsRecordingAndTranscriptionCustomMessage'
    ,'Remove-CsTeamsBYODAndDesksPolicy'
    ,'Remove-CsTeamsNotificationAndFeedsPolicy'
	,'Remove-CsTeamsPersonalAttendantPolicy'
    ,'Set-Team'
    ,'Set-TeamArchivedState'
    ,'Set-TeamChannel'
    ,'Set-TeamPicture'
    ,'Set-TeamsApp'
    ,'Set-CsTeamsAcsFederationConfiguration'
	,'Set-CsTeamsAIPolicy'
    ,'Set-CsTeamsMessagingPolicy'
    ,'Set-CsTeamsMeetingPolicy'
    ,'Set-CsOnlineVoicemailPolicy'
	,'Set-CsTeamsFilesPolicy'
    ,'Set-CsOnlineVoicemailValidationConfiguration'
    ,'Set-CsTeamsFeedbackPolicy'
    ,'Set-CsTeamsUpdateManagementPolicy'
    ,'Set-CsTeamsChannelsPolicy'
	,'Set-CsTeamsMediaConnectivityPolicy'
    ,'Set-CsTeamsMeetingBrandingPolicy'
    ,'Set-CsTeamsEmergencyCallingPolicy'
	,'Set-CsTeamsEducationConfiguration'
    ,'Set-CsTeamsCallHoldPolicy'
    ,'Set-CsTeamsMessagingConfiguration'
	,'Set-CsTeamsVoiceApplicationsPolicy'
    ,'Set-CsTeamsEventsPolicy'
	,'Set-CsTeamsExternalAccessConfiguration'
    ,'Set-CsTeamsCallingPolicy'
	,'Set-CsTeamsClientConfiguration'
    ,'Set-CsExternalAccessPolicy'
    ,'Set-CsTeamsAppPermissionPolicy'
    ,'Set-CsTeamsAppSetupPolicy'
    ,'Set-CsTeamsFirstPartyMeetingTemplateConfiguration'
    ,'Set-CsTeamsMeetingTemplatePermissionPolicy'
	,'Set-CsTeamsMultiTenantOrganizationConfiguration'
    ,'Set-CsLocationPolicy'
    ,'Set-CsTeamsCarrierEmergencyCallRoutingPolicy'
    ,'Set-CsTeamsVirtualAppointmentsPolicy'
    ,'Set-CsTeamsSharedCallingRoutingPolicy'
    ,'Set-CsTeamsTemplatePermissionPolicy'
	,'Set-CsTeamsComplianceRecordingPolicy'
	,'Set-CsTeamsEducationAssignmentsAppPolicy'
	,'Set-CsTeamsComplianceRecordingApplication'
    ,'Set-CsTeamsShiftsPolicy'
    ,'Set-CsTeamsUpgradeConfiguration'
	,'Set-CsTeamsAudioConferencingCustomPromptsConfiguration'
	,'Set-CsTeamsSipDevicesConfiguration'
    ,'Set-CsTeamsMeetingConfiguration'
	,'Set-CsTeamsGuestMeetingConfiguration'
    ,'Set-CsTeamsVdiPolicy'
	,'Set-CsTeamsWorkLocationDetectionPolicy'
	,'Set-CsTeamsRemoteLogCollectionDevice'
    ,'Set-CsTeamsRecordingRollOutPolicy'
	,'Set-CsTeamsRecordingAndTranscriptionCustomMessage'
	,'Set-CsTeamsCustomBannerText'
    ,'Set-CsTeamsBYODAndDesksPolicy'
    ,'Set-CsTeamsNotificationAndFeedsPolicy'
	,'Set-CsTeamsMobilityPolicy'
	,'Set-CsTeamsPersonalAttendantPolicy'
    ,'Set-CsPrivacyConfiguration'
	,'Update-M365TeamsApp'
	,'Update-M365UnifiedTenantSettings'
	,'Update-M365UnifiedCustomPendingApp'

    #MPA OCE cmdlets
    ,'Get-CsBatchOperationDefinition'
    ,'Get-CsBatchOperationStatus'
    ,'Get-CsConfiguration'
    ,'Get-CsGroupPolicyAssignments'
    ,'Get-CsLoginInfo'
    ,'Get-CsUserProvHistory'
    ,'Get-GPAGroupMembers'
    ,'Get-GPAUserMembership'
    ,'Get-NgtProvInstanceFailOverStatus'
    ,'Get-CsTeamsTenantAbuseConfiguration'
    ,'Invoke-CsDirectoryObjectSync'
    ,'Invoke-CsGenericNgtProvCommand'
    ,'Invoke-CsRefreshGroupUsers'
    ,'Invoke-CsReprocessBatchOperation'
    ,'Invoke-CsReprocessGroupPolicyAssignment'
    ,'Move-NgtProvInstance'
    ,'New-CsConfiguration'
    ,'Remove-CsConfiguration'
    ,'Set-CsConfiguration'
    ,'Set-CsTeamsTenantAbuseConfiguration'
	,'Set-CsPublishPolicySchemaDefaults'


#preview    ,'Add-TeamsAppInstallation'
#preview    ,'Get-TeamsAppInstallation'
    ,'Get-TeamTargetingHierarchyStatus'
#preview    ,'Remove-TeamsAppInstallation'
    ,'Remove-TeamTargetingHierarchy'
    ,'Set-TeamTargetingHierarchy'
#preview    ,'Update-TeamsAppInstallation'
#preview    ,'Get-LicenseReportForChangeNotificationSubscription'
    ,'Get-TenantPrivateChannelMigrationStatus'
 )

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = '*'

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{
    PSData = @{
        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = 'Office365', 'MicrosoftTeams', 'Teams'

        # A URL to the license for this module.
        LicenseUri = 'https://raw.githubusercontent.com/MicrosoftDocs/office-docs-powershell/master/teams/LICENSE.txt'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/MicrosoftDocs/office-docs-powershell/tree/master/teams'

        # A URL to an icon representing this module.
        IconUri = 'https://statics.teams.microsoft.com/evergreen-assets/apps/teamscmdlets_largeimage.png'

        # Appends prerelease string to version
        Prerelease = ''

        # ReleaseNotes of this module
        ReleaseNotes = @'
 **7.7.0-GA** (The project - MicrosoftTeams contains changes till this release)
- Fixes IPAddressVersion parameter in [Set|New]-CsOnlinePstnGateway cmdlets.
- Releases [Set|Remove]-CsPhoneNumberSmsActivation cmdlets.
- Adds the SmsActivationState output attribute to the Get-CsPhoneNumberAssignment cmdlet.
- Adds support for application-based authentication in the Set-CsTeamsSettingsCustomApp cmdlet.
- Updates the Get-Team cmdlet to improve performance and reliability.
- [BREAKING CHANGE] Renames ConfigurationId parameter in Get-CsMainlineAttendantFlow cmdlet to RelatedConfigurationId.
- Releases Get-CsMainlineAttendantTenantInformation, Get-CsMainlineAttendantSupportedLanguages, and Get-CsMainlineAttendantSupportedVoices cmdlets.
- Adds AgentId, AgentIds, ContinuationToken, DisplayNameContains, DisplayNamePrefix, MaxResult, and ShowCount parameters to the Get-CsAiAgents cmdlet.
- Adds support for URL-based descriptions in [New|Set]-CsMainlineAttendantQuestionAnswerFlow cmdlets.
- [BREAKING CHANGE] Renames DomainBlockingForMDOAdminsInTeams parameter in Set-CsTenantFederationConfiguration cmdlet to SecurityTeamAllowBlockListDelegation.
- Releases [Get|New|Set|Remove]-CsAgent cmdlets for managing AI agent for resource account integration.
- Adds IncomingRedirectedCalls parameter to New-CsSharedCallQueueHistoryTemplate cmdlet.
- Releases [Get|New|Set|Remove]-CsSharedCallHistoryTemplate cmdlets. These cmdlets will replace [Get|New|Set|Remove]-CsSharedCallQueueHistoryTemplate cmdlets in future.
- Adds SharedVoicemailHistoryTemplateId parameter to New-CsAutoAttendantCallableEntity.
- The complete release notes can be found in the below link:
https://docs.microsoft.com/MicrosoftTeams/teams-powershell-release-notes
'@
    } # End of PSData hashtable
} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''
}

# SIG # Begin signature block
# MIIoLQYJKoZIhvcNAQcCoIIoHjCCKBoCAQExDzANBglghkgBZQMEAgEFADB5Bgor
# BgEEAYI3AgEEoGswaTA0BgorBgEEAYI3AgEeMCYCAwEAAAQQH8w7YFlLCE63JNLG
# KX7zUQIBAAIBAAIBAAIBAAIBADAxMA0GCWCGSAFlAwQCAQUABCBaN75eKur6+Xte
# up7/3/BuJDIEtGF/UFvBF1apbfpw3qCCDXYwggX0MIID3KADAgECAhMzAAAEhV6Z
# 7A5ZL83XAAAAAASFMA0GCSqGSIb3DQEBCwUAMH4xCzAJBgNVBAYTAlVTMRMwEQYD
# VQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNy
# b3NvZnQgQ29ycG9yYXRpb24xKDAmBgNVBAMTH01pY3Jvc29mdCBDb2RlIFNpZ25p
# bmcgUENBIDIwMTEwHhcNMjUwNjE5MTgyMTM3WhcNMjYwNjE3MTgyMTM3WjB0MQsw
# CQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9u
# ZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMR4wHAYDVQQDExVNaWNy
# b3NvZnQgQ29ycG9yYXRpb24wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIB
# AQDASkh1cpvuUqfbqxele7LCSHEamVNBfFE4uY1FkGsAdUF/vnjpE1dnAD9vMOqy
# 5ZO49ILhP4jiP/P2Pn9ao+5TDtKmcQ+pZdzbG7t43yRXJC3nXvTGQroodPi9USQi
# 9rI+0gwuXRKBII7L+k3kMkKLmFrsWUjzgXVCLYa6ZH7BCALAcJWZTwWPoiT4HpqQ
# hJcYLB7pfetAVCeBEVZD8itKQ6QA5/LQR+9X6dlSj4Vxta4JnpxvgSrkjXCz+tlJ
# 67ABZ551lw23RWU1uyfgCfEFhBfiyPR2WSjskPl9ap6qrf8fNQ1sGYun2p4JdXxe
# UAKf1hVa/3TQXjvPTiRXCnJPAgMBAAGjggFzMIIBbzAfBgNVHSUEGDAWBgorBgEE
# AYI3TAgBBggrBgEFBQcDAzAdBgNVHQ4EFgQUuCZyGiCuLYE0aU7j5TFqY05kko0w
# RQYDVR0RBD4wPKQ6MDgxHjAcBgNVBAsTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEW
# MBQGA1UEBRMNMjMwMDEyKzUwNTM1OTAfBgNVHSMEGDAWgBRIbmTlUAXTgqoXNzci
# tW2oynUClTBUBgNVHR8ETTBLMEmgR6BFhkNodHRwOi8vd3d3Lm1pY3Jvc29mdC5j
# b20vcGtpb3BzL2NybC9NaWNDb2RTaWdQQ0EyMDExXzIwMTEtMDctMDguY3JsMGEG
# CCsGAQUFBwEBBFUwUzBRBggrBgEFBQcwAoZFaHR0cDovL3d3dy5taWNyb3NvZnQu
# Y29tL3BraW9wcy9jZXJ0cy9NaWNDb2RTaWdQQ0EyMDExXzIwMTEtMDctMDguY3J0
# MAwGA1UdEwEB/wQCMAAwDQYJKoZIhvcNAQELBQADggIBACjmqAp2Ci4sTHZci+qk
# tEAKsFk5HNVGKyWR2rFGXsd7cggZ04H5U4SV0fAL6fOE9dLvt4I7HBHLhpGdE5Uj
# Ly4NxLTG2bDAkeAVmxmd2uKWVGKym1aarDxXfv3GCN4mRX+Pn4c+py3S/6Kkt5eS
# DAIIsrzKw3Kh2SW1hCwXX/k1v4b+NH1Fjl+i/xPJspXCFuZB4aC5FLT5fgbRKqns
# WeAdn8DsrYQhT3QXLt6Nv3/dMzv7G/Cdpbdcoul8FYl+t3dmXM+SIClC3l2ae0wO
# lNrQ42yQEycuPU5OoqLT85jsZ7+4CaScfFINlO7l7Y7r/xauqHbSPQ1r3oIC+e71
# 5s2G3ClZa3y99aYx2lnXYe1srcrIx8NAXTViiypXVn9ZGmEkfNcfDiqGQwkml5z9
# nm3pWiBZ69adaBBbAFEjyJG4y0a76bel/4sDCVvaZzLM3TFbxVO9BQrjZRtbJZbk
# C3XArpLqZSfx53SuYdddxPX8pvcqFuEu8wcUeD05t9xNbJ4TtdAECJlEi0vvBxlm
# M5tzFXy2qZeqPMXHSQYqPgZ9jvScZ6NwznFD0+33kbzyhOSz/WuGbAu4cHZG8gKn
# lQVT4uA2Diex9DMs2WHiokNknYlLoUeWXW1QrJLpqO82TLyKTbBM/oZHAdIc0kzo
# STro9b3+vjn2809D0+SOOCVZMIIHejCCBWKgAwIBAgIKYQ6Q0gAAAAAAAzANBgkq
# hkiG9w0BAQsFADCBiDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24x
# EDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlv
# bjEyMDAGA1UEAxMpTWljcm9zb2Z0IFJvb3QgQ2VydGlmaWNhdGUgQXV0aG9yaXR5
# IDIwMTEwHhcNMTEwNzA4MjA1OTA5WhcNMjYwNzA4MjEwOTA5WjB+MQswCQYDVQQG
# EwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwG
# A1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSgwJgYDVQQDEx9NaWNyb3NvZnQg
# Q29kZSBTaWduaW5nIFBDQSAyMDExMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIIC
# CgKCAgEAq/D6chAcLq3YbqqCEE00uvK2WCGfQhsqa+laUKq4BjgaBEm6f8MMHt03
# a8YS2AvwOMKZBrDIOdUBFDFC04kNeWSHfpRgJGyvnkmc6Whe0t+bU7IKLMOv2akr
# rnoJr9eWWcpgGgXpZnboMlImEi/nqwhQz7NEt13YxC4Ddato88tt8zpcoRb0Rrrg
# OGSsbmQ1eKagYw8t00CT+OPeBw3VXHmlSSnnDb6gE3e+lD3v++MrWhAfTVYoonpy
# 4BI6t0le2O3tQ5GD2Xuye4Yb2T6xjF3oiU+EGvKhL1nkkDstrjNYxbc+/jLTswM9
# sbKvkjh+0p2ALPVOVpEhNSXDOW5kf1O6nA+tGSOEy/S6A4aN91/w0FK/jJSHvMAh
# dCVfGCi2zCcoOCWYOUo2z3yxkq4cI6epZuxhH2rhKEmdX4jiJV3TIUs+UsS1Vz8k
# A/DRelsv1SPjcF0PUUZ3s/gA4bysAoJf28AVs70b1FVL5zmhD+kjSbwYuER8ReTB
# w3J64HLnJN+/RpnF78IcV9uDjexNSTCnq47f7Fufr/zdsGbiwZeBe+3W7UvnSSmn
# Eyimp31ngOaKYnhfsi+E11ecXL93KCjx7W3DKI8sj0A3T8HhhUSJxAlMxdSlQy90
# lfdu+HggWCwTXWCVmj5PM4TasIgX3p5O9JawvEagbJjS4NaIjAsCAwEAAaOCAe0w
# ggHpMBAGCSsGAQQBgjcVAQQDAgEAMB0GA1UdDgQWBBRIbmTlUAXTgqoXNzcitW2o
# ynUClTAZBgkrBgEEAYI3FAIEDB4KAFMAdQBiAEMAQTALBgNVHQ8EBAMCAYYwDwYD
# VR0TAQH/BAUwAwEB/zAfBgNVHSMEGDAWgBRyLToCMZBDuRQFTuHqp8cx0SOJNDBa
# BgNVHR8EUzBRME+gTaBLhklodHRwOi8vY3JsLm1pY3Jvc29mdC5jb20vcGtpL2Ny
# bC9wcm9kdWN0cy9NaWNSb29DZXJBdXQyMDExXzIwMTFfMDNfMjIuY3JsMF4GCCsG
# AQUFBwEBBFIwUDBOBggrBgEFBQcwAoZCaHR0cDovL3d3dy5taWNyb3NvZnQuY29t
# L3BraS9jZXJ0cy9NaWNSb29DZXJBdXQyMDExXzIwMTFfMDNfMjIuY3J0MIGfBgNV
# HSAEgZcwgZQwgZEGCSsGAQQBgjcuAzCBgzA/BggrBgEFBQcCARYzaHR0cDovL3d3
# dy5taWNyb3NvZnQuY29tL3BraW9wcy9kb2NzL3ByaW1hcnljcHMuaHRtMEAGCCsG
# AQUFBwICMDQeMiAdAEwAZQBnAGEAbABfAHAAbwBsAGkAYwB5AF8AcwB0AGEAdABl
# AG0AZQBuAHQALiAdMA0GCSqGSIb3DQEBCwUAA4ICAQBn8oalmOBUeRou09h0ZyKb
# C5YR4WOSmUKWfdJ5DJDBZV8uLD74w3LRbYP+vj/oCso7v0epo/Np22O/IjWll11l
# hJB9i0ZQVdgMknzSGksc8zxCi1LQsP1r4z4HLimb5j0bpdS1HXeUOeLpZMlEPXh6
# I/MTfaaQdION9MsmAkYqwooQu6SpBQyb7Wj6aC6VoCo/KmtYSWMfCWluWpiW5IP0
# wI/zRive/DvQvTXvbiWu5a8n7dDd8w6vmSiXmE0OPQvyCInWH8MyGOLwxS3OW560
# STkKxgrCxq2u5bLZ2xWIUUVYODJxJxp/sfQn+N4sOiBpmLJZiWhub6e3dMNABQam
# ASooPoI/E01mC8CzTfXhj38cbxV9Rad25UAqZaPDXVJihsMdYzaXht/a8/jyFqGa
# J+HNpZfQ7l1jQeNbB5yHPgZ3BtEGsXUfFL5hYbXw3MYbBL7fQccOKO7eZS/sl/ah
# XJbYANahRr1Z85elCUtIEJmAH9AAKcWxm6U/RXceNcbSoqKfenoi+kiVH6v7RyOA
# 9Z74v2u3S5fi63V4GuzqN5l5GEv/1rMjaHXmr/r8i+sLgOppO6/8MO0ETI7f33Vt
# Y5E90Z1WTk+/gFcioXgRMiF670EKsT/7qMykXcGhiJtXcVZOSEXAQsmbdlsKgEhr
# /Xmfwb1tbWrJUnMTDXpQzTGCGg0wghoJAgEBMIGVMH4xCzAJBgNVBAYTAlVTMRMw
# EQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVN
# aWNyb3NvZnQgQ29ycG9yYXRpb24xKDAmBgNVBAMTH01pY3Jvc29mdCBDb2RlIFNp
# Z25pbmcgUENBIDIwMTECEzMAAASFXpnsDlkvzdcAAAAABIUwDQYJYIZIAWUDBAIB
# BQCgga4wGQYJKoZIhvcNAQkDMQwGCisGAQQBgjcCAQQwHAYKKwYBBAGCNwIBCzEO
# MAwGCisGAQQBgjcCARUwLwYJKoZIhvcNAQkEMSIEIDihBP4iicnzq/pwKABoDTgm
# 2rVVP+J+7Gm/TGpJBBCTMEIGCisGAQQBgjcCAQwxNDAyoBSAEgBNAGkAYwByAG8A
# cwBvAGYAdKEagBhodHRwOi8vd3d3Lm1pY3Jvc29mdC5jb20wDQYJKoZIhvcNAQEB
# BQAEggEAObgcliECs4XlTCsL3BLnuKVnGKXKu7NJesX+97LmEhPNUVFhwFa4HEqN
# dmbHyFYFYzxFpmhtbL3UVAP7OQabUVTGPnRKY/EZ6vI86SUp48N1A+cWlMzc2iZ4
# Hb00Aum81sn8GBjTEuwI/6zizVMayrcdbp8RnodhkY0r4knZwCFSpA1K2ZDZxAQZ
# 5hvdo+U1fMZXNhEjfKdnRK0bjBJ6XKarnLBzjsTcm5u29gbqIkZtG2Wlqw6TwT0j
# pgzLVtzt3pi68V7+3a/wOqwQZXTQkRwK3jKxss/pYSqv6iB/secq8od0f+y6xYUw
# CzpQTndB2RNuch4bMBij8Dmo94sL3KGCF5cwgheTBgorBgEEAYI3AwMBMYIXgzCC
# F38GCSqGSIb3DQEHAqCCF3AwghdsAgEDMQ8wDQYJYIZIAWUDBAIBBQAwggFSBgsq
# hkiG9w0BCRABBKCCAUEEggE9MIIBOQIBAQYKKwYBBAGEWQoDATAxMA0GCWCGSAFl
# AwQCAQUABCBruGRA5YX89Kpm8PfdU4ghW6zdNo0iuflKuT2+FsvFuAIGabsLQn+B
# GBMyMDI2MDMzMTA1MDgzMy43NzNaMASAAgH0oIHRpIHOMIHLMQswCQYDVQQGEwJV
# UzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UE
# ChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSUwIwYDVQQLExxNaWNyb3NvZnQgQW1l
# cmljYSBPcGVyYXRpb25zMScwJQYDVQQLEx5uU2hpZWxkIFRTUyBFU046ODkwMC0w
# NUUwLUQ5NDcxJTAjBgNVBAMTHE1pY3Jvc29mdCBUaW1lLVN0YW1wIFNlcnZpY2Wg
# ghHtMIIHIDCCBQigAwIBAgITMwAAAiJB0vaq/8i1/wABAAACIjANBgkqhkiG9w0B
# AQsFADB8MQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UE
# BxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSYwJAYD
# VQQDEx1NaWNyb3NvZnQgVGltZS1TdGFtcCBQQ0EgMjAxMDAeFw0yNjAyMTkxOTM5
# NTZaFw0yNzA1MTcxOTM5NTZaMIHLMQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2Fz
# aGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENv
# cnBvcmF0aW9uMSUwIwYDVQQLExxNaWNyb3NvZnQgQW1lcmljYSBPcGVyYXRpb25z
# MScwJQYDVQQLEx5uU2hpZWxkIFRTUyBFU046ODkwMC0wNUUwLUQ5NDcxJTAjBgNV
# BAMTHE1pY3Jvc29mdCBUaW1lLVN0YW1wIFNlcnZpY2UwggIiMA0GCSqGSIb3DQEB
# AQUAA4ICDwAwggIKAoICAQC1ueKJukIuUsAAJo/AY5DZRqH7bhgv7CWGNlEdbRGo
# ITrdE6Wsn57NaNu1BTdjBbFcv7Rfixte0x+HRvXSqsD+WeSX/6/y9wE0Mz+xRPTG
# IY20K7aQDa68OyzVyUeUCypyZC/gW/3ytO/ZOnU9H2ri77kJP8ABrqyy1UxX/Ose
# EgvHsj8yikWT0ARtrjWbXMHFzSOo5hQcfUmMXKqWWz6+N0+UynhGy1n+doW4WZgp
# H8Y5W7hpSokWj1M/Lu4wi3o6Dz9vVWukcgUFGjLAl4YZpOhah7HuiC/alXImMQf8
# C3A8q/6/1hFoeIZB4UGkywxB/OSTOSsL6+39pDqzM7CgOpf4V799kN94yM9uXJI5
# T/SiA5MdIZIhEW0+bh85RqDh5YW3/oav54RPxw5OPlH64QV6KJkl0FIElMVoLNo8
# UWRQcMD179x7WASjC6LsaNZ7yK0qcESIsL1wiQmdfQBxcqrFCpIQfnmQFkOp9IyX
# UWqza8tmpz8E6aXg9b1eiAT3PVTgrOlPi/hYZCfPxX/6jGtyPjy1CiwOmJamohmS
# U//COAenfRT2G2HMRUpCX1zs+AmDmdQM1XRab4YSALLAlDzGCsgI77nnuJjoXAli
# Jmv7NfrvWAcA5KqCUOWQ6kSPt5r28MfKXWJJpSXtFeS/MkDzJy/iJRVyHcFy/B+M
# twIDAQABo4IBSTCCAUUwHQYDVR0OBBYEFFkHwGoDJ5ZbEEiu8KstiusqaozQMB8G
# A1UdIwQYMBaAFJ+nFV0AXmJdg/Tl0mWnG1M1GelyMF8GA1UdHwRYMFYwVKBSoFCG
# Tmh0dHA6Ly93d3cubWljcm9zb2Z0LmNvbS9wa2lvcHMvY3JsL01pY3Jvc29mdCUy
# MFRpbWUtU3RhbXAlMjBQQ0ElMjAyMDEwKDEpLmNybDBsBggrBgEFBQcBAQRgMF4w
# XAYIKwYBBQUHMAKGUGh0dHA6Ly93d3cubWljcm9zb2Z0LmNvbS9wa2lvcHMvY2Vy
# dHMvTWljcm9zb2Z0JTIwVGltZS1TdGFtcCUyMFBDQSUyMDIwMTAoMSkuY3J0MAwG
# A1UdEwEB/wQCMAAwFgYDVR0lAQH/BAwwCgYIKwYBBQUHAwgwDgYDVR0PAQH/BAQD
# AgeAMA0GCSqGSIb3DQEBCwUAA4ICAQBiAM+nqrpwG29txSXv42o+CsTe2C4boaRf
# Fju9JaWkLTHwq7pknNONL3n+UG3x/B083EKXiFYrAmul7BTHCGXU63/xRsZ2wj3Z
# mR0A4d9nf9saCJVm4juPVFBai/oktOOYH2j+1+zM70woN5ongB/pvy7X8AfY6JB4
# XPvb80Qz7fY5eddbnwjzg1sZhUPFbbcweWeACINrzqFK62mMeXKmhtufMraoogJe
# JXfWY3x4/pbubgENT3+pXT65203CPF9kfdKE7GKAIRYy3xkBTDvFd8dufjOpCn38
# nK6qMlVtnBjDhWQG0PM3E/oxBs5UBrI6pBYkmIHtbjifDquHT+ThaVV7xHc6InoS
# c3aNzX49JHUgQmuvDdMjLkbYXeA0/1q5IxSg2U+ycZBOvAi3udZPKhA5VzODjf/u
# cu/vFtXrYcRkmGKN3jujaK3/yMZi2Ju5NEL3ISWorwp7RjeZg+JMIK0fosuVj+YC
# m5r64LH/D9QJDAj+XfZaNeFdv90K5A0QRRGP/poB9yTIVjEXj/uJzp8L4Dd44sAq
# uqDOiHdkLgxfK8nPqpCSWPZ9G+RCPm85o9cAfxENtrSuOwcpyKzxsRCYCL+PK4+9
# 8orit9EVJ/LLoCeG+jLlj0KaD4Qy6sZe4rWMr1brQLosTBZNwFnXxNjInCWBd0i7
# is1yTS/4qTCCB3EwggVZoAMCAQICEzMAAAAVxedrngKbSZkAAAAAABUwDQYJKoZI
# hvcNAQELBQAwgYgxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAw
# DgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24x
# MjAwBgNVBAMTKU1pY3Jvc29mdCBSb290IENlcnRpZmljYXRlIEF1dGhvcml0eSAy
# MDEwMB4XDTIxMDkzMDE4MjIyNVoXDTMwMDkzMDE4MzIyNVowfDELMAkGA1UEBhMC
# VVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNV
# BAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEmMCQGA1UEAxMdTWljcm9zb2Z0IFRp
# bWUtU3RhbXAgUENBIDIwMTAwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoIC
# AQDk4aZM57RyIQt5osvXJHm9DtWC0/3unAcH0qlsTnXIyjVX9gF/bErg4r25Phdg
# M/9cT8dm95VTcVrifkpa/rg2Z4VGIwy1jRPPdzLAEBjoYH1qUoNEt6aORmsHFPPF
# dvWGUNzBRMhxXFExN6AKOG6N7dcP2CZTfDlhAnrEqv1yaa8dq6z2Nr41JmTamDu6
# GnszrYBbfowQHJ1S/rboYiXcag/PXfT+jlPP1uyFVk3v3byNpOORj7I5LFGc6XBp
# Dco2LXCOMcg1KL3jtIckw+DJj361VI/c+gVVmG1oO5pGve2krnopN6zL64NF50Zu
# yjLVwIYwXE8s4mKyzbnijYjklqwBSru+cakXW2dg3viSkR4dPf0gz3N9QZpGdc3E
# XzTdEonW/aUgfX782Z5F37ZyL9t9X4C626p+Nuw2TPYrbqgSUei/BQOj0XOmTTd0
# lBw0gg/wEPK3Rxjtp+iZfD9M269ewvPV2HM9Q07BMzlMjgK8QmguEOqEUUbi0b1q
# GFphAXPKZ6Je1yh2AuIzGHLXpyDwwvoSCtdjbwzJNmSLW6CmgyFdXzB0kZSU2LlQ
# +QuJYfM2BjUYhEfb3BvR/bLUHMVr9lxSUV0S2yW6r1AFemzFER1y7435UsSFF5PA
# PBXbGjfHCBUYP3irRbb1Hode2o+eFnJpxq57t7c+auIurQIDAQABo4IB3TCCAdkw
# EgYJKwYBBAGCNxUBBAUCAwEAATAjBgkrBgEEAYI3FQIEFgQUKqdS/mTEmr6CkTxG
# NSnPEP8vBO4wHQYDVR0OBBYEFJ+nFV0AXmJdg/Tl0mWnG1M1GelyMFwGA1UdIARV
# MFMwUQYMKwYBBAGCN0yDfQEBMEEwPwYIKwYBBQUHAgEWM2h0dHA6Ly93d3cubWlj
# cm9zb2Z0LmNvbS9wa2lvcHMvRG9jcy9SZXBvc2l0b3J5Lmh0bTATBgNVHSUEDDAK
# BggrBgEFBQcDCDAZBgkrBgEEAYI3FAIEDB4KAFMAdQBiAEMAQTALBgNVHQ8EBAMC
# AYYwDwYDVR0TAQH/BAUwAwEB/zAfBgNVHSMEGDAWgBTV9lbLj+iiXGJo0T2UkFvX
# zpoYxDBWBgNVHR8ETzBNMEugSaBHhkVodHRwOi8vY3JsLm1pY3Jvc29mdC5jb20v
# cGtpL2NybC9wcm9kdWN0cy9NaWNSb29DZXJBdXRfMjAxMC0wNi0yMy5jcmwwWgYI
# KwYBBQUHAQEETjBMMEoGCCsGAQUFBzAChj5odHRwOi8vd3d3Lm1pY3Jvc29mdC5j
# b20vcGtpL2NlcnRzL01pY1Jvb0NlckF1dF8yMDEwLTA2LTIzLmNydDANBgkqhkiG
# 9w0BAQsFAAOCAgEAnVV9/Cqt4SwfZwExJFvhnnJL/Klv6lwUtj5OR2R4sQaTlz0x
# M7U518JxNj/aZGx80HU5bbsPMeTCj/ts0aGUGCLu6WZnOlNN3Zi6th542DYunKmC
# VgADsAW+iehp4LoJ7nvfam++Kctu2D9IdQHZGN5tggz1bSNU5HhTdSRXud2f8449
# xvNo32X2pFaq95W2KFUn0CS9QKC/GbYSEhFdPSfgQJY4rPf5KYnDvBewVIVCs/wM
# nosZiefwC2qBwoEZQhlSdYo2wh3DYXMuLGt7bj8sCXgU6ZGyqVvfSaN0DLzskYDS
# PeZKPmY7T7uG+jIa2Zb0j/aRAfbOxnT99kxybxCrdTDFNLB62FD+CljdQDzHVG2d
# Y3RILLFORy3BFARxv2T5JL5zbcqOCb2zAVdJVGTZc9d/HltEAY5aGZFrDZ+kKNxn
# GSgkujhLmm77IVRrakURR6nxt67I6IleT53S0Ex2tVdUCbFpAUR+fKFhbHP+Crvs
# QWY9af3LwUFJfn6Tvsv4O+S3Fb+0zj6lMVGEvL8CwYKiexcdFYmNcP7ntdAoGokL
# jzbaukz5m/8K6TT4JDVnK+ANuOaMmdbhIurwJ0I9JZTmdHRbatGePu1+oDEzfbzL
# 6Xu/OHBE0ZDxyKs6ijoIYn/ZcGNTTY3ugm2lBRDBcQZqELQdVTNYs6FwZvKhggNQ
# MIICOAIBATCB+aGB0aSBzjCByzELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hp
# bmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jw
# b3JhdGlvbjElMCMGA1UECxMcTWljcm9zb2Z0IEFtZXJpY2EgT3BlcmF0aW9uczEn
# MCUGA1UECxMeblNoaWVsZCBUU1MgRVNOOjg5MDAtMDVFMC1EOTQ3MSUwIwYDVQQD
# ExxNaWNyb3NvZnQgVGltZS1TdGFtcCBTZXJ2aWNloiMKAQEwBwYFKw4DAhoDFQC7
# ycXVZx3bsDpJkr7VucgpksozuKCBgzCBgKR+MHwxCzAJBgNVBAYTAlVTMRMwEQYD
# VQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNy
# b3NvZnQgQ29ycG9yYXRpb24xJjAkBgNVBAMTHU1pY3Jvc29mdCBUaW1lLVN0YW1w
# IFBDQSAyMDEwMA0GCSqGSIb3DQEBCwUAAgUA7XVaMjAiGA8yMDI2MDMzMDIwMjMx
# NFoYDzIwMjYwMzMxMjAyMzE0WjB3MD0GCisGAQQBhFkKBAExLzAtMAoCBQDtdVoy
# AgEAMAoCAQACAiVxAgH/MAcCAQACAhOUMAoCBQDtdquyAgEAMDYGCisGAQQBhFkK
# BAIxKDAmMAwGCisGAQQBhFkKAwKgCjAIAgEAAgMHoSChCjAIAgEAAgMBhqAwDQYJ
# KoZIhvcNAQELBQADggEBAEZA8b6iSWkRf+pHiw+8/tfRntUphCSDLLhuUw6HJ/Dc
# ikGFRNAw2MJ8MhpNp0foxmCR9vcqXTp5QETOpUWXzCewcGrVOMHm3gALFnOvQxN4
# oCnPwyPwqPM6Au396ft5giFgwf6k1LQLg5HlRV/rTyLqz3IyJ0Ec3enV3N+6EZn8
# ggADoKZ7xAk7Y/PTGuzpKEoW5mmMD62q9QxRbqFN2QJBQIeBR2uGKi9MnBXAt3/R
# zQWxyr2Wwo5gfYBdAkZZNlMTGGmsD5gp/cOssI5uImNaNfSNr4O8wjt48GUArgeD
# 5bnUFu4VBoiOpZpcDByu1MupbnXxvz0OjA4EC56njoExggQNMIIECQIBATCBkzB8
# MQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVk
# bW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSYwJAYDVQQDEx1N
# aWNyb3NvZnQgVGltZS1TdGFtcCBQQ0EgMjAxMAITMwAAAiJB0vaq/8i1/wABAAAC
# IjANBglghkgBZQMEAgEFAKCCAUowGgYJKoZIhvcNAQkDMQ0GCyqGSIb3DQEJEAEE
# MC8GCSqGSIb3DQEJBDEiBCAYkDn68LEfuISvI6C5eFPE+dUbCm4gDFZOWmXc0e/n
# lzCB+gYLKoZIhvcNAQkQAi8xgeowgecwgeQwgb0EIAVgXQEKBOfGgjNskmDOmbcE
# IOnHGNwA+QcRufDR5AkTMIGYMIGApH4wfDELMAkGA1UEBhMCVVMxEzARBgNVBAgT
# Cldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29m
# dCBDb3Jwb3JhdGlvbjEmMCQGA1UEAxMdTWljcm9zb2Z0IFRpbWUtU3RhbXAgUENB
# IDIwMTACEzMAAAIiQdL2qv/Itf8AAQAAAiIwIgQgTmlUiGJfDuN9DXMjGYW7xVs+
# CveDYVaRxoQ/dSXyNH4wDQYJKoZIhvcNAQELBQAEggIAElkMfiaNp0eaYBXtMHRN
# WfWq7RkHqkoQ6VLMTFRFGwDiuntGh8y/4iAjU3qmv/d3D6I0YHUHwIm21KVf6W5m
# q9vJkzRd/P8vrQbBsfDYyhpD95MqPQuvcYFZ5KwzyafswCxQNAm/DBE3kgb8/TNh
# Y+qw0cxmJgufGlUHYLlC0hqzCJyTBcWAmVNEX3ShqfYcsGWII/VEE/YHJE6S11dW
# AMb70DkKqYdr3Kd8yLQkCY8RXd8Nx7NQRnZmdqjrXF0LgTwBXEP1YrtzCTazMnPQ
# mu+zGpxtUcx7xEY/ASdPXrG5BKHg5RhrAWBfa4rsjzQY7SnHhHC/vLlGWWJhdAYh
# ek5847+hghvp+IqlH05yqcwyOrKoCXAl097VU7f0pjKDEpzcZKptm6+IySfTbviU
# IJxaSFKDqmTQsCHRBjJcstzjeXBZpaJ1QMSvNCzsH6HhraJRzEj7aoRQOV9S5x+t
# ELAPU2L/wjRAY+VH+v4fYLB6jVhKi+JpW/ouKg+SN38pMQw8vCRlS6qJhiR7DbdY
# R3ShFv9XNJtPgDxXqeQ9WwYf0pJJ6om2p58h087FjmuroVHxmp70P6EbJ79OQPuB
# SWLiYKaT+a7YawPNwowJLf1+00KmoVewxqySVJj6B28KyaKC71Rel5jFZOEpbilW
# vDNvwuJEtWk88Lv4qIng16k=
# SIG # End signature block
